ExamProject/Controllers/EspaceLocataireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamProject.Models;
using ExamProject.Models.viewModel;
using Microsoft.AspNetCore.Identity;
using ExamProject.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace ExamProject.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
    public class EspaceLocataireController : Controller
    {
        private readonly CarsRentalContext _context;
        EspaceLocataireVM espaceLocataireVM;
        private readonly UserManager<ApplicationUser> userManager;
        public ApplicationUser ApplicationUser;

        public EspaceLocataireController(CarsRentalContext context, UserManager<ApplicationUser> _userManager)
        {
            _context = context;
            espaceLocataireVM = new EspaceLocataireVM()
            {
                voitures = _context.Voiture.ToList(),
                searchedCar = ""

            };
            userManager = _userManager;
            foreach (var ele in espaceLocataireVM.voitures)
            {
                var appuser = _context.applicationUsers.Where(ap => ap.ProprietaireId == ele.ProprietaireId).First();
                ele.ApplicationUser = appuser;

                if (!ele.EstDisponible)
                {
                    var location = _context.locations.Where(l => l.VoitureId == ele.Id).FirstOrDefault();

                    int result  =DateTime.Compare(location.DateFin, DateTime.Now);
                    if (result < 0)
                    {
                        ele.EstDisponible = true;
                        _context.SaveChanges();
                    }
                }
            }
            

        }

        
        public IActionResult Index(int page = 0, int size = 2)
        {
            int position = page * size;
            espaceLocataireVM.voitures = _context.Voiture.Skip(position).Take(size). Include(v => v.Marque).Include(v => v.Model).ToList();
            ViewBag.currentPage = page;
            int totalPages;
            int nbre = _context.Voiture.ToList().Count;
            if (nbre % size == 0)
            {
                totalPages = nbre / size;
            }
            else
            {
                totalPages = 1 + nbre / size;
            }
            ViewBag.totalPages = totalPages;
            return View(espaceLocataireVM);
        }

        [HttpPost]
        public IActionResult Index(string color, string Marque, string prix, string disponibilite, string keyword="")
        {
            if (color != null || Marque != null || prix != null || disponibilite!=null)  /*Contains("")*/
            {
                if (color == null)
                {
                    color = "";
                }
                if (Marque == null)
                {
                    Marque = "";
                }
                if (prix == null)
                {
                    prix = "";
                }
                if(disponibilite== "diponible")
                {
                    espaceLocataireVM.voitures = _context.Voiture.Include(v => v.Marque).Include(v => v.Model).Where(p => p.Couleur.Contains(color) && p.Marque.NomMarque.Contains(Marque) && p.PrixParJour.Contains(prix) && p.EstDisponible == true).ToList();
                }
                else if(disponibilite== "occupe")
                {
                    espaceLocataireVM.voitures = _context.Voiture.Include(v => v.Marque).Include(v => v.Model).Where(p => p.Couleur.Contains(color) && p.Marque.NomMarque.Contains(Marque) && p.PrixParJour.Contains(prix) && p.EstDisponible==false).ToList();
                }else
                espaceLocataireVM.voitures = _context.Voiture.Include(v => v.Marque).Include(v => v.Model).Where(p => p.Couleur.Contains(color) && p.Marque.NomMarque.Contains(Marque) && p.PrixParJour.Contains(prix)).ToList();
                //var marquedata = _context.Voiture.Where(A) ;
                return View(espaceLocataireVM);
            }
            else
            {
                if (String.IsNullOrEmpty(keyword)) return Index();
                espaceLocataireVM.voitures = _context.Voiture.Include(v => v.Marque).Include(v => v.Model).Where(v => v.Marque.NomMarque.Contains(keyword) || v.Model.NomModel.Contains(keyword)).ToList();
                ViewBag.keyword = keyword;
                return View(espaceLocataireVM);
            }
        }
        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> GetUsers()
        {
            var users = userManager.Users;
            List<ApplicationUser> usersList = new List<ApplicationUser>();
            foreach (var user in userManager.Users)
            {
                if (!(await userManager.IsInRoleAsync(user, Roles.Executive) || await userManager.IsInRoleAsync(user, Roles.Executive)))
                {
                    usersList.Add(user);
                }
            }
            return View(usersList);
        }
        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> GetUsers2()
        {
            var users = userManager.Users;
            List<ApplicationUser> usersList = new List<ApplicationUser>();
            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, Roles.Executive) || await userManager.IsInRoleAsync(user, Roles.Executive))
                {
                    usersList.Add(user);
                }
            }
            return View(usersList);
        }
        [Authorize(Roles = Roles.Admin)]
        // GET: EspaceLocataire/RemoveRoleAsync
        [HttpGet]
        public async Task<IActionResult> RemoveRole(string Id)
        {

            ApplicationUser = await userManager.FindByIdAsync(Id.ToString());
            //await userManager.RemoveFromRoleAsync(user, Roles.Executive);
            //var users = userManager.Users;
            return View(ApplicationUser);
        }
        [Authorize(Roles = Roles.Admin)]
        [HttpPost]
        public async Task<IActionResult> RemoveRoleAsync(string Id)
        {

            var user = await userManager.FindByIdAsync(Id.ToString());
            await userManager.RemoveFromRoleAsync(user, Roles.Executive);
            var users = userManager.Users;
            return RedirectToAction(nameof(GetUsers));
        }
        [Authorize(Roles = Roles.Admin)]
        // GET: EspaceLocataire/RemoveRoleAsync
        [HttpGet]
        public async Task<IActionResult> GiveRole(string Id)
        {

            ApplicationUser = await userManager.FindByIdAsync(Id.ToString());
            //await userManager.RemoveFromRoleAsync(user, Roles.Executive);
            //var users = userManager.Users;
            return View(ApplicationUser);
        }
        [Authorize(Roles = Roles.Admin)]
        [HttpPost]
        public async Task<IActionResult> GiveRoleAsync(string Id)
        {

            var user = await userManager.FindByIdAsync(Id.ToString());
            await userManager.AddToRoleAsync(user, Roles.Executive);
            var users = userManager.Users;
            return RedirectToAction(nameof(GetUsers));
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voiture = _context.Voiture.Include(v => v.Marque).Include(v => v.Model)
                .First(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            return View(voiture);
        }
        

        public IActionResult Allouer(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voiture = espaceLocataireVM.voitures
                .First(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            return View(voiture);
        }
        // GET: EspaceLocataire/Create
        public IActionResult Create()
        {
            ViewData["MarqueID"] = new SelectList(_context.Marques, "Id", "NomMarque");
            ViewData["ModelID"] = new SelectList(_context.Models, "Id", "NomModel");
            return View();
        }

        // POST: EspaceLocataire/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> confirmAllouer( string startingDate,string endingDate,int carid)
        {
            string[] sd = startingDate.Split("-");
            string[] ed = endingDate.Split("-");
            DateTime startd = new DateTime(Convert.ToInt32(sd[0]), Convert.ToInt32(sd[1]), Convert.ToInt32(sd[2]));
            DateTime endd = new DateTime(Convert.ToInt32(ed[0]), Convert.ToInt32(ed[1]), Convert.ToInt32(ed[2]));

            var car = _context.Voiture.Where(v => v.Id == carid).FirstOrDefault();
            if (car.EstDisponible == true) { 
            var user = _context.applicationUsers.Where(ap => ap.UserName == User.Identity.Name).First();
            Location location = new Location() {
                DateDebut =startd,
                DateFin =endd,
                LocataireId =user.LocataireId,
                PrixTotal=(endd-startd).TotalDays * Convert.ToDouble(car.PrixParJour),
                VoitureId =carid,
                statut="demande envoyé"
                
            };
               

            _context.locations.Add(location);
                car.EstDisponible = false;
            _context.SaveChanges();
                var locationid = _context.locations.Max(l => l.Id);

ExamProject/Views/EspaceLocataire/Allouer.cshtml
@model ExamProject.Models.Voiture

@{
    ViewData["Title"] = "Allouer";
}


<h4>Choisir la periode d'allocation</h4>

<div style="width:60%;margin:auto">
    <div class="ui center aligned">
        <form method="post" class="ui form" asp-action="confirmAllouer">
            <div class="field">
                <div class="ui calendar">
                    <div class="ui input left icon">
                        <i class="calendar icon"></i>
                        <input type="date" placeholder="starting date" name="startingDate">
                    </div>
                </div>
            </div>


            <input type="hidden" name="carid" value="@Model.Id">

            <div class="field">
                <div class="ui calendar">
                    <div class="ui input left icon">
                        <i class="calendar icon"></i>
                        <input type="date" placeholder="ending dte" name="endingDate">
                    </div>
                </div>
            </div>
            <input type="submit" class="ui button teal" value="allouer">
            
           
        </form>
        </div>
</div>

ExamProject/Views/EspaceLocataire/Details.cshtml
@model ExamProject.Models.Voiture
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@using ExamProject.Helpers
@{
    ViewData["Title"] = "Details";
}

<h2 class="ui center aligned whiteBG" style="width:70%;margin-bottom:2em">@Html.DisplayFor(model => model.Marque.NomMarque) @Html.DisplayFor(model => model.Model.NomModel)</h2>

<div class="ui grid center aligned">

    <div class="ui eleven wide column whiteBG">
        <div class="image" style="padding-top:10px">
            <img src="../../@Html.DisplayFor(model => model.ImagePath)" width="100%" style="max-height:1000px" />
        </div>
        <div class="">

        </div>
        <div class="ui grid description">
            <div class="ui four wide column"><span class="ui sub header">@_localizer["Price Per Day"]: </span></div>
            <div class="ui twelve wide column"><span class="ui tag label ui green">@Html.DisplayFor(modelItem => modelItem.PrixParJour) MAD</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Make"]:</span> </div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Marque.NomMarque)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Model"]:</span> </div>
            <div class="ui twelve wide column"><span class="ui label"> @Html.DisplayFor(modelItem => modelItem.Model.NomModel)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Year"]:</span></div>
            <span class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Annee)</span></span>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Color"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Couleur)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Kilometrage)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Kilometrage)</span></div>


            <div class="ui four wide column"><span class="ui sub header">@_localizer["nom de proprietaire"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => Model.ApplicationUser.Nom) @Html.DisplayFor(modelItem => Model.ApplicationUser.Prenom)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["tele"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.ApplicationUser.PhoneNumber)</span></div>
            <div class="ui four wide column"><span class="ui sub header">@_localizer["diponibilité"]: </span></div>

            @if (Model.EstDisponible)
            {
                <div class="ui twelve wide column"><span class="ui green label">@_localizer["diponible"]</span></div>
            }
            else
            {
                <div class="ui twelve wide column"><span class="ui red label">@_localizer["occupe"]</span></div>
            }

        </div>
        <div class="ui whiteBG">
            <div class="ui center aligned extra">
                @if (User.IsInRole(Roles.Admin))
                {
                    <a asp-controller="Voitures" asp-action="Edit" asp-route-id="@Model.Id" class="ui tiny labeled icon button blue"><i class=" ui icon edit"></i>@_localizer["Edit"]</a>
                    <a asp-controller="Voitures" asp-action="Delete" asp-route-id="@Model.Id" class="ui tiny labeled icon button red"><i class=" ui icon trash"></i>@_localizer["Delete"]</a>}
                    <a asp-action="Index" class="ui tiny green labeled icon button"><i class=" ui icon arrow left"></i>@_localizer["Back to List"]</a>
                </div>
        </div>

    </div>

    <div class="ui four wide column whiteBG center aligned" style="padding-top:2em">
        @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
        {
            <a asp-action="Allouer" asp-route-id="@Model.Id" class="ui tiny teal labeled icon big button center aligned"><i class="ui icon plus"></i>@_localizer["Allouer"]</a>
            <br />
            <br />
            <a asp-action="ajouterFavori" asp-route-id="@Model.Id" class="ui tiny yellow labeled icon button"><i class=" ui icon star"></i>@_localizer["ajouter aux favoris"]</a>
            <hr />}
        <h3>Description</h3>
        <div>
            @Html.DisplayFor(modelItem => modelItem.Description)
        </div>
    </div>
</div>

ExamProject/Views/EspaceLocataire/Edit.cshtml
@model ExamProject.Models.Voiture

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Voiture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PrixParJour" class="control-label"></label>
                <input asp-for="PrixParJour" class="form-control" />
                <span asp-validation-for="PrixParJour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Annee" class="control-label"></label>
                <input asp-for="Annee" class="form-control" />
                <span asp-validation-for="Annee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kilometrage" class="control-label"></label>
                <input asp-for="Kilometrage" class="form-control" />
                <span asp-validation-for="Kilometrage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarqueID" class="control-label"></label>
                <select asp-for="MarqueID" class="form-control" asp-items="ViewBag.MarqueID"></select>
                <span asp-validation-for="MarqueID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelID" class="control-label"></label>
                <select asp-for="ModelID" class="form-control" asp-items="ViewBag.ModelID"></select>
                <span asp-validation-for="ModelID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProprietaireId" class="control-label"></label>
                <select asp-for="ProprietaireId" class="form-control" asp-items="ViewBag.ProprietaireId"></select>
                <span asp-validation-for="ProprietaireId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Couleur" class="control-label"></label>
                <input asp-for="Couleur" class="form-control" />
                <span asp-validation-for="Couleur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Immatriculation" class="control-label"></label>
                <input asp-for="Immatriculation" class="form-control" />
                <span asp-validation-for="Immatriculation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamProject/Views/EspaceLocataire/GetUsers.cshtml
@model IEnumerable<ApplicationUser>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@{
    ViewData["Title"] = "The Blacklist";
}

    <h2>@_localizer["blacklist"]</h2>
<table class="ui table striped">
    <thead>
        <tr>
            <th>
                @_localizer["First Name"]
            </th>
            <th>
                @_localizer["Last Name"]
            </th>
            <th>
                @_localizer["Phone Number"]
            </th>
            <th>
                @_localizer["Email"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="GiveRole" asp-route-id="@item.Id" class="ui tiny labeled icon button green"><i class=" ui icon warning"></i>@_localizer["Remove from blacklist"]</a>
            </td>
        </tr>
        }
    </tbody>
</table>

ExamProject/Views/EspaceLocataire/GetUsers2.cshtml
@model IEnumerable<ApplicationUser>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@{
    ViewData["Title"] = "GetUsers";
}

    <h2>@_localizer["All Users"]</h2>
<table class="ui table striped">
    <thead>
        <tr>
            <th>
                @_localizer["First Name"]
            </th>
            <th>
                @_localizer["Last Name"]
            </th>
            <th>
                @_localizer["Phone Number"]
            </th>
            <th>
                @_localizer["Email"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenom)
                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="RemoveRole" asp-route-id="@item.Id" class="ui tiny labeled icon button red"><i class=" ui icon warning"></i>@_localizer["Add To Blacklist"]</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ExamProject/Views/EspaceLocataire/GiveRole.cshtml
@model ApplicationUser
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@{
    ViewData["Title"] = "GiveRole";
}

<h2>GiveRoleAsync</h2>

<h3>@_localizer["Are you sure you want to do this?"] : <span class="ui green label">@_localizer["User Name"] : @Html.DisplayFor(model => model.UserName)</span></h3>


<form asp-action="GiveRoleAsync">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="ui tiny labeled icon button red"><i class=" ui icon green"></i>@_localizer["Add To List"]</button>
    <a asp-action="GetUsers">@_localizer["Back to List"]</a>
</form>

ExamProject/Views/EspaceLocataire/Index.cshtml
@model ExamProject.Models.viewModel.EspaceLocataireVM
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@using ExamProject.Helpers
@{
    ViewData["Title"] = "Index";
}

    <div style="width:80%;margin:auto">
        <form asp-controller="EspaceLocataire" asp-action="Index">
            <div class="ui form">
                <div class="five fields">
                    <input type="text" id="prix" class="ui field input" name="prix" placeholder="@_localizer["Enter a price"]" aria-describedby="basic-addon1" />
                    <input type="text" id="color" class="ui field input" name="color" placeholder="@_localizer["Enter a color"]" aria-describedby="basic-addon1" />
                    <input type="text" id="Marque" class="ui field input" name="Marque" placeholder="@_localizer["Enter a make"]" aria-describedby="basic-addon1" />

                    <select class="ui search dropdown field" name="disponibilite">
                        <option value="diponible">@_localizer["Available"]</option>
                        <option value="occupe">@_localizer["Occupied"]</option>
               
                        <option value="tous">@_localizer["All"]</option>
                    </select>
                        <button type="submit" class="ui tiny teal labeled icon button field"><i class=" ui icon search"></i>@_localizer["Search by criteria"]</button>
</div>
            </div>
        </form>
        @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
        {
            <p>
                <a asp-action="myRents" class="ui blue button"><i class="ui icon car"></i>@_localizer["My rents"]</a>
                <a asp-action="favorites" class="ui yellow button"><i class="ui icon star"></i>@_localizer["My favorits"]</a>
            </p>
        }
        <form method="post" enctype="multipart/form-data" asp-action="Index">
            <div class="ui fluid icon input center">
                <input type="text" asp-for="searchedCar" name="keyword" value="@ViewBag.keyword" placeholder="@_localizer["Enter your keyword"]">
                <i class="search icon"></i>
            </div>
        </form>

        <div class="ui items">
            @foreach (var item in Model.voitures)
            {
                <div class="ui item" style="background:white;border:1px solid #ccc;margin:1.5em;">
                    <div class="image">
                        <img src="@Html.DisplayFor(modelItem => item.ImagePath)" />
                    </div>
                    <div class="content">

                        <div class="header padded">@Html.DisplayFor(modelItem => item.Marque.NomMarque) @Html.DisplayFor(modelItem => item.Model.NomModel)</div>
                        <span class="meta ui green text"> @Html.DisplayFor(modelItem => item.PrixParJour) MAD / @_localizer["Day"]</span>

                        <div class="ui grid description">
                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Price Per Day"]: </span></div>
                            <div class="ui twelve wide column"><span class="ui tag label ui green">@Html.DisplayFor(modelItem => item.PrixParJour) MAD</span></div>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Make"]:</span> </div>
                            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Marque.NomMarque)</span></div>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Model"]:</span> </div>
                            <div class="ui twelve wide column"><span class="ui label"> @Html.DisplayFor(modelItem => item.Model.NomModel)</span></div>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Year"]:</span></div>
                            <span class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Annee)</span></span>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Color"]: </span></div>
                            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Couleur)</span></div>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
                            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Kilometrage)</span></div>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
                            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Kilometrage)</span></div>


                            <div class="ui four wide column"><span class="ui sub header">@_localizer["nom de proprietaire"]: </span></div>
                            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.ApplicationUser.Nom)</span></div>

                            <div class="ui four wide column"><span class="ui sub header">@_localizer["tele"]: </span></div>
                            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.ApplicationUser.PhoneNumber)</span></div>
                            <div class="ui four wide column"><span class="ui sub header">@_localizer["diponibilité"]: </span></div>

                            @if (item.EstDisponible)
                            {
                                <div class="ui twelve wide column"><span class="ui label">@_localizer["diponible"]</span></div>
                            }
                            else
                            {
                                <div class="ui twelve wide column"><span class="ui label">@_localizer["occupe"]</span></div>
                            }
                        </div>

                        <span class="ui center aligned extra">
                            <a asp-action="Details" asp-route-id="@item.Id" class="ui tiny blue labeled icon button"><i class=" ui icon info"></i>@_localizer["Details"]</a>
                            @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                            {
                                <a asp-action="Allouer" asp-route-id="@item.Id" class="ui tiny teal labeled icon button"><i class=" ui icon plus"></i>@_localizer["Allocate"]</a>
                                <a asp-action="ajouterFavori" asp-route-id="@item.Id" class="ui tiny yellow labeled icon button"><i class=" ui icon star"></i>@_localizer["Add to favorites"]</a>}
                        </span>
                    </div>
                </div>
            }
        </div>
            <div class="ui pagination menu">
                @{
                    for (int i = 0; i < ViewBag.totalPages; i++)
                    {
                        string className = "item";
                        if (i == ViewBag.currentPage)
                        {
                            className = "active item";
                        }
                        <a class="@className" asp-action="Index" asp-route-page="@i" asp-route-motCle="@ViewBag.motCle">@(i + 1)</a>
                    }
                }
            </div>
            <div class="clear"></div>

        </div>

ExamProject/Views/EspaceLocataire/RemoveRole.cshtml
@model ApplicationUser
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@{
    ViewData["Title"] = "RemoveRole";
}

<h2>RemoveRoleAsync</h2>

<h3>@_localizer["Are you sure you want to do this?"] : <span class="ui green label">@_localizer["User Name"] : @Html.DisplayFor(model => model.UserName)</span></h3>


<form asp-action="RemoveRoleAsync">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="ui tiny labeled icon button red"><i class=" ui icon warning"></i>@_localizer["Add To Blacklist"]</button>
    <a asp-action="GetUsers">@_localizer["Back to List"]</a>
</form>