ExamProject/Controllers/MarquesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamProject.Models;
using ExamProject.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Localization;

namespace ExamProject.Controllers
{
    [Authorize(Roles = Roles.Admin)]
    public class MarquesController : Controller
    {
        private readonly CarsRentalContext _context;

        public MarquesController(CarsRentalContext context)
        {
            _context = context;
        }
        //private readonly IStringLocalizer<MarquesController> _localizer;

        //public MarquesController(IStringLocalizer<MarquesController> localizer)
        //{
        //    _localizer = localizer;
        //}

        // GET: Marques
        public async Task<IActionResult> Index(string marques)
        {
            if (marques != null)
            {
                var marquedata = _context.Marques.Where(p => p.NomMarque.Contains(marques)).ToList();
                return View(marquedata);
            }
            else
            {
                return View(await _context.Marques.ToListAsync());
            }
        }


        // GET: Marques/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marque = await _context.Marques
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marque == null)
            {
                return NotFound();
            }

            return View(marque);
        }

        // GET: Marques/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Marque marque)
        {
            if (ModelState.IsValid)
            {
                _context.Add(marque);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(marque);
        }

        // GET: Marques/Edit/5
        public IActionResult Edit(int id)
        {
            var marque =_context.Marques.Find(id);
            if (marque == null)
            {
                return NotFound();
            }
            return View(marque);
        }

        // POST: Marques/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public IActionResult Edit(Marque marque)
        {
            if (ModelState.IsValid)
            {
               _context.Update(marque);
               _context.SaveChanges();
                return RedirectToAction(nameof(Index));  
            }
            return View(marque);
        }

        // GET: Marques/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marque = await _context.Marques
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marque == null)
            {
                return NotFound();
            }

            return View(marque);
        }

        // POST: Marques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Marque marque = _context.Marques.Find(id);
            _context.Marques.Remove(marque);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }        
    }
}

ExamProject/Controllers/ModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamProject.Models;
using ExamProject.Models.viewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using ExamProject.Helpers;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Localization;

namespace ExamProject.Controllers
{
    
    public class ModelsController : Controller
    {
        private readonly IStringLocalizer<ModelsController> _localizer;

        private readonly CarsRentalContext _context;
        [BindProperty]
        public ModelVM VM { get; set; }
        public ModelsController(CarsRentalContext context, IStringLocalizer<ModelsController> localizer)
        {
            _context = context;
            _localizer = localizer;
            VM = new ModelVM()
            {
                Marques = _context.Marques.ToList(),
                Model = new Models.Model()
            };
        }

        [Authorize(Roles = Roles.Admin)]
        public IActionResult Index(string models)
        {
            if (models != null)
            {
                var marquedata = _context.Models.Where(p => (p.NomModel.Contains(models)) || p.Marque.NomMarque.Contains(models)).ToList();
                return View(marquedata);
            }
            else
            {
                var model = _context.Models.Include(m => m.Marque);
                return View(model.ToList());
            }
        }

        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [Authorize(Roles = Roles.Admin)]
        public List<Marque> FillSelectList()
        {
            var makes = _context.Marques.ToList();
            makes.Insert(0, new Marque { Id = -1, NomMarque = _localizer["--- Please select a Make--"] });
            return makes;
        }
        [Authorize(Roles = Roles.Admin)]
        ModelVM GetAllMakes()
        {
            var vmodel = new ModelVM
            {
                Marques = FillSelectList()
            };
            return vmodel;
        }
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Create()
        {
            return View(GetAllMakes());
        }

        // POST: Models/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Create(IFormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View(VM);
            }
            _context.Models.Add(VM.Model);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = Roles.Admin)]
        public IActionResult Edit(int id)
        {
            VM.Model = _context.Models.Include(m => m.Marque).SingleOrDefault(m => m.Id == id);
            if (VM.Model == null)
            {
                return NotFound();
            }

            return View(VM);
        }

        // POST: Models/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [Authorize(Roles = Roles.Admin)]
        [HttpPost]
        public IActionResult Edit()
        {
            if (!ModelState.IsValid)
            {
                return View(VM);
            }
            _context.Update(VM.Model);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [Authorize(Roles = Roles.Admin)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Model model = _context.Models.Find(id);
            _context.Models.Remove(model);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        //private bool ModelExists(int id)
        //{
        //    return _context.Models.Any(e => e.Id == id);
        //}
        [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
        [HttpGet("api/models/{MarqueID}")]
        public IEnumerable<Model> Models(int MarqueID)
        {
            return _context.Models.ToList()
            .Where(m => m.MarqueID == MarqueID);
        }
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

ExamProject/Views/Shared/_Layout.cshtml
@using ExamProject.Helpers
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamProject</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link href="~/lib/jqueryui/jquery-ui.css" rel="stylesheet" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/semantic-ui/semantic.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link href="~/lib/semantic-ui/semantic.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div style="width:90%">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img width="110px" src="~/images/logoCarRental.png" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                    {
                        <li><a asp-area="" asp-controller="Voitures" asp-action="">@_localizer["Owners board"]</a></li>

                        <li><a asp-area="" asp-controller="EspaceLocataire" asp-action="Index">@_localizer["Rental board"]</a></li>
                    }
                    @if (User.IsInRole(Roles.Admin))
                    {
                        <li><a asp-area="" asp-controller="Models" asp-action="">@_localizer["Models"]</a></li>
                        <li><a asp-area="" asp-controller="Marques" asp-action="">@_localizer["Makes"]</a></li>
                    }
                    @if (User.IsInRole(Roles.Admin))
                    {
                        <li><a asp-area="" asp-controller="EspaceLocataire" asp-action="GetUsers">@_localizer["Blacklist"]</a></li>
                        <li><a asp-area="" asp-controller="EspaceLocataire" asp-action="GetUsers2">@_localizer["Users' list"]</a></li>
}
                    @if (User.IsInRole(Roles.Admin))
                    {
                        <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-page="/Account/Register">@_localizer["Add user"]</a></li>
                    }
                </ul>

                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div style="width:95%;margin:auto;margin-top:4em;">
        @if ((User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive)) && this.ViewContext.RouteData.Values["controller"] != null || this.ViewContext.RouteData.Values["action"] != null )
        {
            <div class="ui breadcrumb">
                <a class="section" asp-controller="Home" asp-action="Index"><i class="ui icon home"></i>Car Rental</a>
                <i class="right chevron icon divider"></i>
                <a asp-area="" asp-controller="@this.ViewContext.RouteData.Values["controller"].ToString()" asp-action="Index" class="section">@this.ViewContext.RouteData.Values["controller"].ToString()</a>
                <i class="right chevron icon divider"></i>
                <div class="active section">@this.ViewContext.RouteData.Values["action"].ToString()</div>
            </div>
        }
        @RenderBody()

    </div>
    <hr style="border-top:1px solid #ccc;" />
    <footer>
        @{
            string year = DateTime.Now.Year.ToString();
        }
        <div class="ui grid center aligned">
            <div class="ui column six wide">
                <p>&copy; @year - CarRental</p>
            </div>
            <div class="ui column six wide">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </div>
    </footer>
    <script src="~/lib/semantic-ui/components/dimmer.js"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/semantic-ui/semantic.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/lib/semantic-ui/semantic.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ExamProject/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>>
    <environment include="Development">
        <link href="~/lib/semantic-ui/semantic.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link href="~/lib/semantic-ui/semantic.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style type="text/css">

        body {
            background-color: #DADADA;
        }

            body > .grid {
                height: 100%;
            }

        .image {
            margin-top: -100px;
        }

        .column {
            max-width: 450px;
        }
    </style>
</head>
<body>
    <partial name="_CookieConsentPartial" />
    <div>
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/semantic-ui/semantic.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>

        <script src="~/lib/semantic-ui/semantic.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

ExamProject/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] <select name="culture"
                                        asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems" class="ui dropdown"></select>
        <button type="submit" class="ui button teal">Save</button>

    </form>
</div>