ExamProject/Models/Demande.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProject.Models
{
    public class Demande
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public int voitureid { get; set; }
        public Voiture voiture { get; set; }
        public Location location { get; set; }
        public string etat { get; set; }

    }
}

ExamProject/Models/Voiture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProject.Models
{
    public class Voiture
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Provide Price")]
        public string PrixParJour { get; set; }

        [Required(ErrorMessage = "Provide Year")]
        public string Annee { get; set; }

        [Required(ErrorMessage = "Provide Mileage")]
        [Range(1, int.MaxValue, ErrorMessage = "This Mileage is Invalid")]
        public string Kilometrage { get; set; }

        public Marque Marque { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Select a Make")]
        public int MarqueID { get; set; }

        public Model Model { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Select a Model")]
        public int ModelID { get; set; }

        public int ProprietaireId { get; set; }
        public string Couleur { get; set; }

        public string Immatriculation { get; set; }

        public string Description { get; set; }
        public string ImagePath { get; set; }

        public ApplicationUser ApplicationUser { get; set; }

        public bool EstDisponible { get; set; }
    }
}

ExamProject/Controllers/VoituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamProject.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting.Internal;
using ExamProject.Models.viewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using ExamProject.Helpers;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Localization;

namespace ExamProject.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
    public class VoituresController : Controller
    {
        private readonly CarsRentalContext _context;
        private readonly HostingEnvironment _hostingEnvironment;
        [BindProperty]
        public CarViewModel VM { get; set; }
        private readonly IStringLocalizer<VoituresController> _localizer;
        public VoituresController(CarsRentalContext context ,HostingEnvironment hostingEnvironment, IStringLocalizer<VoituresController> localizer)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            VM = new CarViewModel()
            {
                Marques = _context.Marques.ToList(),
                Models = _context.Models.ToList(),
                Voiture = new Models.Voiture(),
            };
            _localizer = localizer;
        }

        // GET: Voitures
        public IActionResult Index(string annees, string color, string Marque, string prix)
        {
            var currentUser = _context.applicationUsers.Where(a => a.UserName == User.Identity.Name).First();
            if (annees != null || color != null || Marque != null || prix != null)  /*Contains("")*/
            {
                if (color == null)
                {
                    color = "";
                }
                if (Marque == null)
                {
                    Marque = "";
                }
                if (annees == null)


                {
                    annees = "";
                }
                if (prix == null)
                {
                    prix = "";
                }
                var marquedata = _context.Voiture.Where(p => p.Annee.Contains(annees) && p.Couleur.Contains(color) && p.Marque.NomMarque.Contains(Marque) && p.PrixParJour.Contains(prix)).ToList();
                //var marquedata = _context.Voiture.Where(A) ;
                return View(marquedata);
            }
            else
            {
                var voitures = _context.Voiture.Include(m => m.Marque).Include(m => m.Model).Where(v => v.ProprietaireId == currentUser.ProprietaireId);
                return View(voitures);
            }

        }

        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voiture
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            return View(voiture);
        }
        public List<Marque> FillSelectList()
        {
            var makes = _context.Marques.ToList();
            makes.Insert(0, new Marque { Id = -1, NomMarque = "--- Veuillez selectionner une marque--" });
            return makes;
        }
        public List<Model> FillSelectListModels()
        {
            var models = _context.Models.ToList();
            models.Insert(0, new Model { Id = -1, NomModel = "--- Veuillez selectionner un model--" });
            return models;
        }
        CarViewModel GetAllMakes()
        {
            var vmodel = new CarViewModel
            {
                Marques = FillSelectList(),
                Models = FillSelectListModels()
            };
            return vmodel;
        }
        // GET: Voitures/Create
        public IActionResult Create()
        {
            return View(GetAllMakes());
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(IFormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View(VM);
            }
            var currentUser = _context.applicationUsers.Where(a => a.UserName == User.Identity.Name).First();
            VM.Voiture.ProprietaireId =  currentUser.ProprietaireId ;
            VM.Voiture.EstDisponible = true;
            _context.Voiture.Add(VM.Voiture);
            _context.SaveChanges();
            int CarID = _context.Voiture.Max(v => v.Id);
            UploadImage(CarID);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Voitures/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {
            VM.Voiture = _context.Voiture.SingleOrDefault(b => b.Id == id);
            VM.Models = _context.Models.Where(m => m.MarqueID == VM.Voiture.MarqueID);
            if (VM.Voiture == null)
            {
                return NotFound();
            }
            return View(VM);
        }

        [HttpPost]
        public IActionResult Edit()
        {
            if (!ModelState.IsValid)
            {
                VM.Marques = _context.Marques.ToList();
                VM.Models = _context.Models.ToList();
                return View(VM);
            }
            if (VM.Voiture.ModelID == 0)
            {
                ViewBag.Message = "Please select a Model from the list";
                return View(VM);
            }
            var currentUser = _context.applicationUsers.Where(a => a.UserName == User.Identity.Name).First();
            VM.Voiture.ProprietaireId = currentUser.ProprietaireId;
            _context.Voiture.Update(VM.Voiture);
            UploadImage(VM.Voiture.Id);

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Voitures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voiture
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            return View(voiture);
        }
        
         public IActionResult accepter(int? id)
        {
            var demande = _context.demande.FirstOrDefault(d => d.Id == id);
            demande.etat = "demande acceptée";
            var location = _context.locations.FirstOrDefault(l => l.VoitureId == demande.voitureid);
            location.statut = "demande rejetée";
            _context.SaveChanges();
            return RedirectToAction(nameof(demandes));
        }

        public IActionResult rejter(int? id)
        {
            var demande = _context.demande.FirstOrDefault(d => d.Id == id);
            demande.etat = "demande rejetée";
            var location = _context.locations.FirstOrDefault(l => l.VoitureId == demande.voitureid);
            location.statut = "demande rejetée";
            _context.SaveChanges();
            return RedirectToAction(nameof(demandes));
        }
        // POST: Voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
             Voiture voiture = _context.Voiture.Find(id);
            _context.Voiture.Remove(voiture);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool VoitureExists(int id)
        {
            return _context.Voiture.Any(e => e.Id == id);
        }


        private void UploadImage(int CarID)
        {

            

            //Get wwwroot path to save the file on server 
            string wwwrootPath = _hostingEnvironment.WebRootPath;
            //Get the aploaded files
            var files = HttpContext.Request.Form.Files;

            var SavedCar = _context.Voiture.Find(CarID);

            if (files.Count != 0)
            {
                var ImagePath = @"images\cars\";
                var Extension = Path.GetExtension(files[0].FileName);
                var RelativeImagePath = ImagePath + CarID + Extension;
                var AbsImagePath = Path.Combine(wwwrootPath, RelativeImagePath);
                //Upload the file on server
              using (var fileStream = new FileStream(AbsImagePath, FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                //Set the image path on database
               SavedCar.ImagePath = RelativeImagePath;

            }
        }
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public IActionResult demandes()
        {
            var currentUser = _context.applicationUsers.Where(a => a.UserName == User.Identity.Name).First();
            var cars = _context.Voiture.Where(p => p.ProprietaireId == currentUser.ProprietaireId).ToList();

            List<Demande> Demandes = new List<Demande>();

            foreach(var ele in cars)
            {
                var item = _context.demande.FirstOrDefault(d => d.voitureid == ele.Id);
                if (item != null)
                {

                    item.voiture = ele;
                item.location = _context.locations.FirstOrDefault(l => l.VoitureId == item.voitureid);
                Demandes.Add(item);
                }

ExamProject/Views/Voitures/Create.cshtml
@model ExamProject.Models.viewModel.CarViewModel

@{
    ViewData["Title"] = "create a car";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <script>
    $(document).ready(function () {
        var MakeDDL = $("#Marque");
        var ModelDDL = $("#Model");
        ModelDDL.prop('disabled', true);
        MakeDDL.change(function () {
            if ($(this).val() == "0") {
                ModelDDL.prop('disabled', true);
                ModelDDL.val("0");
            }
            else {
                $.ajax({
                    url: "/api/models/" +$(this).val(),
                    method: "get",
                    success: function (data) {
                        ModelDDL.prop('disabled', false);
                        ModelDDL.empty();
                        ModelDDL.append($('<option/>', { value: '0', text: '--Select Model--' }));
                        $(data).each(function (index, item) {
                            ModelDDL.append($('<option/>', { value: item.id, text: item.nomModel }));
                        });
                    }
                });
            }
        });
    });
    </script>
<h1>Create</h1>

<h4>Voiture</h4>
<hr />
<div style="width:60%;margin:auto">
    <div class="ui center aligned">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marques"></label>
                <select asp-for="Voiture.MarqueID" asp-items="@(new SelectList(Model.Marques,"Id","NomMarque"))" class="form-control" id="Marque"></select>
                <span asp-validation-for="Voiture.MarqueID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Models"></label>
                <select asp-for="Voiture.ModelID" asp-items="@(new SelectList(Model.Models,"Id","NomModel"))" class="form-control" id="Model"></select>
                <span asp-validation-for="Voiture.ModelID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voiture.PrixParJour" class="control-label"></label>
                <input asp-for="Voiture.PrixParJour" class="form-control" />
                <span asp-validation-for="Voiture.PrixParJour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voiture.Annee" class="control-label"></label>
                <input asp-for="Voiture.Annee" class="form-control" />
                <span asp-validation-for="Voiture.Annee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voiture.Kilometrage" class="control-label"></label>
                <input asp-for="Voiture.Kilometrage" class="form-control" />
                <span asp-validation-for="Voiture.Kilometrage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voiture.Couleur" class="control-label"></label>
                <input asp-for="Voiture.Couleur" class="form-control" />
                <span asp-validation-for="Voiture.Couleur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voiture.Description" class="control-label"></label>
                <textarea rows="3" asp-for="Voiture.Description" class="form-control" ></textarea>
                <span asp-validation-for="Voiture.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voiture.ImagePath" class="control-label"></label>
                <input type="file" asp-for="Voiture.ImagePath" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="ui button teal" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamProject/Views/Voitures/Delete.cshtml
@model ExamProject.Models.Voiture

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Voiture</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrixParJour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrixParJour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Annee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Annee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kilometrage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kilometrage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Couleur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Couleur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExamProject/Views/Voitures/Details.cshtml
@model ExamProject.Models.Voiture
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@using ExamProject.Helpers
@{
    ViewData["Title"] = "Details";
}

<h2 class="ui center aligned whiteBG" style="width:70%;margin-bottom:2em">@Html.DisplayFor(model => model.Marque.NomMarque) @Html.DisplayFor(model => model.Model.NomModel)</h2>

<div class="ui grid center aligned">

    <div class="ui eleven wide column whiteBG">
        <div class="image" style="padding-top:10px">
            <img src="../../@Html.DisplayFor(model => model.ImagePath)" width="100%" style="max-height:1000px" />
        </div>
        <div class="">

        </div>
        <div class="ui grid description">
            <div class="ui four wide column"><span class="ui sub header">@_localizer["Price Per Day"]: </span></div>
            <div class="ui twelve wide column"><span class="ui tag label ui green">@Html.DisplayFor(modelItem => modelItem.PrixParJour) MAD</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Make"]:</span> </div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Marque.NomMarque)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Model"]:</span> </div>
            <div class="ui twelve wide column"><span class="ui label"> @Html.DisplayFor(modelItem => modelItem.Model.NomModel)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Year"]:</span></div>
            <span class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Annee)</span></span>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Color"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Couleur)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Kilometrage)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
            <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => modelItem.Kilometrage)</span></div>

            <div class="ui four wide column"><span class="ui sub header">@_localizer["diponibilité"]: </span></div>

            @if (Model.EstDisponible)
            {
                <div class="ui twelve wide column"><span class="ui label">@_localizer["diponible"]</span></div>
            }
            else
            {
                <div class="ui twelve wide column"><span class="ui label">@_localizer["occupe"]</span></div>
            }

        </div>
        <div class="ui whiteBG">
            <div class="ui center aligned extra">
                @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                {
                    <a asp-controller="Voitures" asp-action="Edit" asp-route-id="@Model.Id" class="ui tiny labeled icon button blue"><i class=" ui icon edit"></i>@_localizer["Edit"]</a>
                    <a asp-controller="Voitures" asp-action="Delete" asp-route-id="@Model.Id" class="ui tiny labeled icon button red"><i class=" ui icon trash"></i>@_localizer["Delete"]</a>}
                <a asp-action="Index" class="ui tiny green labeled icon button"><i class=" ui icon arrow left"></i>@_localizer["Back to List"]</a>
            </div>
        </div>

    </div>

    <div class="ui four wide column whiteBG center aligned" style="padding-top:2em">

        <h3>Description</h3>
        <div>
            @Html.DisplayFor(modelItem => modelItem.Description)
        </div>
        <hr />
        <div>
            <h3>Historique</h3>
            Lorem ipsum bla bla bla
            bla bla bla bla bla bla
        </div>
    </div>
</div>

ExamProject/Views/Voitures/Edit.cshtml
@model ExamProject.Models.viewModel.CarViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@{
    ViewData["Title"] = "Edit a car";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    $(document).ready(function () {
        var MakeDDL = $("#Marque");
        var ModelDDL = $("#Model");
        // ModelDDL.prop('disabled', true);
        MakeDDL.change(function () {
            if ($(this).val() == "0") {
                ModelDDL.prop('disabled', true);
                ModelDDL.val("0");
            }
            else {
                $.ajax({
                    url: "/api/models/" + $(this).val(),
                    method: "get",
                    success: function (data) {
                        ModelDDL.prop('disabled', false);
                        ModelDDL.empty();
                        ModelDDL.append($('<option/>', { value: '0', text: '--Select Model--' }));
                        $(data).each(function (index, item) {
                            ModelDDL.append($('<option/>', { value: item.id, text: item.nomModel }));
                        });
                    }
                });
            }
        });
    });
</script>
<h1>Edit</h1>

<h4>Voiture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" action="Edit">
            <input hidden asp-for="Voiture.Id" />
            <input hidden asp-for="Voiture.ImagePath" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marques">@_localizer["Makes"]</label>
                <select asp-for="Voiture.MarqueID" asp-items="@(new SelectList(Model.Marques,"Id","NomMarque"))" class="form-control" id="Marque"></select>
                <span asp-validation-for="Voiture.MarqueID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@_localizer["Models"]</label>
                <select asp-for="Voiture.ModelID" asp-items="@(new SelectList(Model.Models,"Id","NomModel"))" class="form-control" id="Model"></select>
                <span asp-validation-for="Voiture.ModelID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@_localizer["Price Per Day"]</label>
                <input asp-for="Voiture.PrixParJour" class="form-control" />
                <span asp-validation-for="Voiture.PrixParJour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@_localizer["Year"]</label>
                <input asp-for="Voiture.Annee" class="form-control" />
                <span asp-validation-for="Voiture.Annee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@_localizer["Mileage"]</label>
                <input asp-for="Voiture.Kilometrage" class="form-control" />
                <span asp-validation-for="Voiture.Kilometrage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@_localizer["Color"]</label>
                <input asp-for="Voiture.Couleur" class="form-control" />
                <span asp-validation-for="Voiture.Couleur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@_localizer["Picture"]</label>
                <input type="file" asp-for="Voiture.ImagePath" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="@_localizer["Edit"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@_localizer["Back to List"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamProject/Views/Voitures/Index.cshtml
@model IEnumerable<ExamProject.Models.Voiture>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@using ExamProject.Helpers
@{
    ViewData["Title"] = "Index";
}

<h1>@_localizer["My cars"]</h1>
<form asp-controller="Voitures" asp-action="Index">
    <div class="ui form">
        <div class="four fields">
            <input type="text" id="prix" class="ui field input" name="prix" placeholder="@_localizer["Enter a price"]" aria-describedby="basic-addon1" />
            <input type="text" id="color" class="ui field input" name="color" placeholder="@_localizer["Enter a color"]" aria-describedby="basic-addon1" />
            <input type="text" id="Marque" class="ui field input" name="Marque" placeholder="@_localizer["Enter a make"]" aria-describedby="basic-addon1" />
            <button type="submit" class="ui tiny teal labeled icon button field"><i class=" ui icon search"></i>@_localizer["Search by criteria"]</button>
        </div>
    </div>
</form>
<p>
    <a asp-action="Create" class="ui green button"><i class="ui icon add"></i>@_localizer["Create New"]</a>
    <a asp-action="demandes" class="ui blue button"><i class="ui icon list ul"></i>@_localizer["Demandes"]</a>
</p>
<div class="ui items">
    @foreach (var item in Model)
    {
        <div class="ui item" style="background:white;border:1px solid #ccc;margin:1.5em;">
            <div class="image">
                <img src="@Html.DisplayFor(modelItem => item.ImagePath)" />
            </div>
            <div class="content">

                <div class="header padded">@Html.DisplayFor(modelItem => item.Marque.NomMarque) @Html.DisplayFor(modelItem => item.Model.NomModel)</div>
                <span class="meta ui green text"> @Html.DisplayFor(modelItem => item.PrixParJour) MAD / >@_localizer["Day"]</span>

                <div class="ui grid description">
                    <div class="ui four wide column"><span class="ui sub header">@_localizer["Price Per Day"]: </span></div>
                    <div class="ui twelve wide column"><span class="ui tag label ui green">@Html.DisplayFor(modelItem => item.PrixParJour) MAD</span></div>

                    <div class="ui four wide column"><span class="ui sub header">@_localizer["Make"]:</span> </div>
                    <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Marque.NomMarque)</span></div>

                    <div class="ui four wide column"><span class="ui sub header">@_localizer["Model"]:</span> </div>
                    <div class="ui twelve wide column"><span class="ui label"> @Html.DisplayFor(modelItem => item.Model.NomModel)</span></div>

                    <div class="ui four wide column"><span class="ui sub header">@_localizer["Year"]:</span></div>
                    <span class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Annee)</span></span>

                    <div class="ui four wide column"><span class="ui sub header">@_localizer["Color"]: </span></div>
                    <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Couleur)</span></div>

                    <div class="ui four wide column"><span class="ui sub header">@_localizer["Mileage"]: </span></div>
                    <div class="ui twelve wide column"><span class="ui label">@Html.DisplayFor(modelItem => item.Kilometrage)</span></div>





                </div>

                <span class="ui center aligned extra">
                    @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="ui tiny labeled icon button blue"><i class=" ui icon edit"></i>@_localizer["Edit"]</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="ui tiny labeled icon button red"><i class=" ui icon trash"></i>@_localizer["Delete"]</a>}
                    <a asp-action="Details" asp-route-id="@item.Id" class="ui tiny teal labeled icon button"><i class=" ui icon info"></i>@_localizer["Details"]</a>
                </span>
            </div>
        </div>
    }
</div>
<div class="clear"></div>
@section Scripts {
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {

            //var MakeDDL = $("#Marque");
            //var ModelDDL = $("#Model");
            //ModelDDL.prop('disabled', true);
            //MakeDDL.change(function () {
            //    if ($(this).val() == "0") {
            //        ModelDDL.prop('disabled', true);
            //        ModelDDL.val("0");
            //    }
            //    else {
            //        $.ajax({
            //            url: "/api/models/" +$(this).val(),
            //            method: "get",
            //            success: function (data) {
            //                ModelDDL.prop('disabled', false);
            //                ModelDDL.empty();
            //                ModelDDL.append($('<option/>', { value: '0', text: '--Select Model--' }));
            //                $(data).each(function (index, item) {
            //                    ModelDDL.append($('<option/>', { value: item.id, text: item.nomModel }));
            //                });
            //            }
            //        });
            //    }
            //});

            //$("#Model").autocomplete({
            //    source: 'api/voitureapi/searchml' + $("#Marque").val(),
            //    });


            $("#Marque").autocomplete({
                source: 'api/voitureapi/searchmk'
            });
            $("#prix").autocomplete({
                source: 'api/voitureapi/searchp'
            });
            $("#color").autocomplete({
                source: 'api/voitureapi/searchc'
            });

        });</script>

}